/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class DoiMatKhau extends javax.swing.JDialog {

    private String Username;

    public DoiMatKhau(JFrame parent,boolean modal,String Username) {
        super(parent, modal);
        initComponents();
        this.Username = Username;
        setTitle("Đổi mật khẩu");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Txt_Username.setText(Username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lb_Title = new javax.swing.JLabel();
        Lb_Tentaikhoan = new javax.swing.JLabel();
        Lb_Matkhaumoi = new javax.swing.JLabel();
        Lb_Nhaplai = new javax.swing.JLabel();
        Txt_Username = new javax.swing.JTextField();
        Btn_Accept = new javax.swing.JButton();
        Btn_Reset = new javax.swing.JButton();
        Lb_Matkhaucu = new javax.swing.JLabel();
        Txt_Matkhaucu = new javax.swing.JPasswordField();
        Txt_Matkhaumoi = new javax.swing.JPasswordField();
        Txt_Nhaplai = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Lb_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lb_Title.setForeground(new java.awt.Color(0, 102, 204));
        Lb_Title.setText("Đổi mật khẩu");

        Lb_Tentaikhoan.setText("Tên tài khoản:");

        Lb_Matkhaumoi.setText("Mật khẩu mới:");

        Lb_Nhaplai.setText("Nhập lại mật khẩu mới:");

        Txt_Username.setEditable(false);

        Btn_Accept.setText("Accept");
        Btn_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AcceptActionPerformed(evt);
            }
        });

        Btn_Reset.setText("Reset");
        Btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ResetActionPerformed(evt);
            }
        });

        Lb_Matkhaucu.setText("Mật khẩu cũ:");

        Txt_Matkhaucu.setToolTipText("");
        Txt_Matkhaucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MatkhaucuActionPerformed(evt);
            }
        });

        Txt_Matkhaumoi.setToolTipText("Mật khẩu chỉ được phép 8 ký tự");

        Txt_Nhaplai.setToolTipText("Mật khẩu chỉ được phép 8 ký tự");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Btn_Accept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb_Tentaikhoan)
                            .addComponent(Lb_Matkhaucu)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lb_Nhaplai, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lb_Matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Username)
                            .addComponent(Txt_Matkhaucu)
                            .addComponent(Txt_Matkhaumoi)
                            .addComponent(Txt_Nhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 72, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(Lb_Title)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(Lb_Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Tentaikhoan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Matkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Matkhaucu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Matkhaumoi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Nhaplai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Nhaplai))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ResetActionPerformed
        Txt_Matkhaucu.setText("");
        Txt_Matkhaumoi.setText("");
        Txt_Nhaplai.setText("");
    }//GEN-LAST:event_Btn_ResetActionPerformed

    private void Btn_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AcceptActionPerformed
        if (Txt_Matkhaucu.getText().isEmpty() | Txt_Matkhaumoi.getText().isEmpty() | Txt_Nhaplai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được bỏ trống ô!");
        } else if (!Txt_Matkhaumoi.getText().equalsIgnoreCase(Txt_Nhaplai.getText())) {
            JOptionPane.showMessageDialog(null, "Mật khẩu nhập lại không khớp mật khẩu mới!");
        } else if (Txt_Matkhaumoi.getText().length() >=9 | Txt_Nhaplai.getText().length() >= 9) {
            JOptionPane.showMessageDialog(null, "Mật khẩu chỉ được phép chứa 8 ký tự!");
        } else {
            boolean Status = new Model.DoiMatKhau().CheckOldPass(Username, Txt_Matkhaucu.getText());
            if (Status == true) {
                boolean Status1 = new Model.DoiMatKhau().ChangePass(Username, Txt_Matkhaumoi.getText());
                if (Status1 == true) {
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công!");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu không thành công!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Mật khẩu cũ không đúng\nĐổi mật khẩu thất bại!");
            }
        }
    }//GEN-LAST:event_Btn_AcceptActionPerformed

    private void Txt_MatkhaucuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MatkhaucuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MatkhaucuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DoiMatKhau().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Accept;
    private javax.swing.JButton Btn_Reset;
    private javax.swing.JLabel Lb_Matkhaucu;
    private javax.swing.JLabel Lb_Matkhaumoi;
    private javax.swing.JLabel Lb_Nhaplai;
    private javax.swing.JLabel Lb_Tentaikhoan;
    private javax.swing.JLabel Lb_Title;
    private javax.swing.JPasswordField Txt_Matkhaucu;
    private javax.swing.JPasswordField Txt_Matkhaumoi;
    private javax.swing.JPasswordField Txt_Nhaplai;
    private javax.swing.JTextField Txt_Username;
    // End of variables declaration//GEN-END:variables
}
