/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan;

import Model.LoaiHang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Stack;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Toan
 */
public class QLLoaiHang extends javax.swing.JDialog {

    /**
     * Creates new form themloaihang
     */
    private Connection cnt = new connectDB.connectDB().getConnection();
    DefaultTableModel tblModel;
    Vector<String> tieude;
    Vector<String> row;
    Vector<Object> data;

    public QLLoaiHang(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Quản lý loại hàng");
        tieude = new Vector<>();
        tieude.add("Mã cung cấp");
        tieude.add("Mã loại hàng");
        tieude.add("Tên loại hàng");
        row = new Vector<>();
        data = new Vector<>();
        tblModel = new DefaultTableModel(data, tieude) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblLoaihang.setModel(tblModel);
        loaddata();
        loadCombobox();
        getInfo01();
        hidejbtLH(false);
        hidejbtSX(false);
        setLocationRelativeTo(null);
        setResizable(false);
//        cboNhaCC.setSelectedIndex(0);
    }

    public void loaddata() {
        String sql = "select ccLoaiHang.maNhaCC, ccLoaiHang.maLH, tenLH\n"
                + "                from ccLoaiHang\n"
                + "                inner join LoaiHang on ccLoaiHang.maLH = LoaiHang.maLH\n"
                + "                inner join NhaCC on ccLoaiHang.maNhaCC = NhaCC.maNhaCC\n"
                + "                where LoaiHang.status = 1\n"
                + "                order by ccLoaiHang.maNhaCC asc";
        try {

            Statement stm = cnt.createStatement();
            ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                data.add(v);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Có lỗi khi lấy dữ liệu từ database!");
        }
    }

    public void loadCombobox() {
        try {
            String sql = "select maNhacc from NhaCC where status = 1";
            Statement stm = cnt.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                this.cboNhaCC.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            Logger.getLogger(QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void getInfo01() {
        this.cboNhaCC.setSelectedItem(tblLoaihang.getValueAt(0, 0));
        txtMaLH.setText(tblLoaihang.getValueAt(0, 1).toString());
        txtTenLH.setText(tblLoaihang.getValueAt(0, 2).toString());

    }

    private void hidejbtLH(boolean status) {
        jbtLuu.setEnabled(status);
        jbtHuy.setEnabled(status);
    }

    private void hidejbtSX(boolean status) {
        jbtSua.setEnabled(status);
        jbtXoa.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaLH = new javax.swing.JTextField();
        txtTenLH = new javax.swing.JTextField();
        jbtThem = new javax.swing.JButton();
        jbtSua = new javax.swing.JButton();
        jbtXoa = new javax.swing.JButton();
        jbtLuu = new javax.swing.JButton();
        jbtThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaihang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cboNhaCC = new javax.swing.JComboBox<>();
        jbtHuy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Quản lý loại hàng");

        jLabel2.setText("Mã loại hàng");

        jLabel3.setText("Tên loại hàng");

        txtMaLH.setEditable(false);

        jbtThem.setText("Thêm");
        jbtThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemActionPerformed(evt);
            }
        });

        jbtSua.setText("Sửa");
        jbtSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSuaActionPerformed(evt);
            }
        });

        jbtXoa.setText("Xóa");
        jbtXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXoaActionPerformed(evt);
            }
        });

        jbtLuu.setText("Lưu");
        jbtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLuuActionPerformed(evt);
            }
        });

        jbtThoat.setText("Thoát");
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        tblLoaihang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoaihang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaihangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaihang);

        jLabel4.setText("Nhà cung cấp");

        cboNhaCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn --" }));
        cboNhaCC.setToolTipText("");
        cboNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNhaCCActionPerformed(evt);
            }
        });

        jbtHuy.setText("Hủy");
        jbtHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHuyActionPerformed(evt);
            }
        });

        jLabel5.setText("Tìm kiếm");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboNhaCC, 0, 176, Short.MAX_VALUE)
                    .addComponent(txtMaLH)
                    .addComponent(txtTenLH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtThem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtThem)
                            .addComponent(jbtLuu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtXoa)
                            .addComponent(jbtSua, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtHuy)
                            .addComponent(jbtThoat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLuuActionPerformed
        // TODO add your handling code here:
        boolean Status = new LoaiHang().themLoaiHang(txtMaLH.getText(), txtTenLH.getText(), this.cboNhaCC.getSelectedItem().toString());
        if (Status = true) {
            Vector<String> v = new Vector<>();
            v.add(this.cboNhaCC.getSelectedItem().toString());
            v.add(txtMaLH.getText());
            v.add(txtTenLH.getText());
            data.add(v);
            tblLoaihang.updateUI();
            txtMaLH.setEditable(false);
            hidejbtLH(false);
            hidejbtSX(true);
        }
    }//GEN-LAST:event_jbtLuuActionPerformed

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtThoatActionPerformed

    private void tblLoaihangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaihangMouseClicked
        // TODO add your handling code here:
        cboNhaCC.setSelectedItem(tblLoaihang.getValueAt(tblLoaihang.getSelectedRow(), 0).toString());
        txtMaLH.setText(tblLoaihang.getValueAt(tblLoaihang.getSelectedRow(), 1).toString());
        txtTenLH.setText(tblLoaihang.getValueAt(tblLoaihang.getSelectedRow(), 2).toString());
        hidejbtSX(true);
    }//GEN-LAST:event_tblLoaihangMouseClicked

    private void jbtThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemActionPerformed
        // TODO add your handling code here:
        txtMaLH.setEditable(true);
        txtMaLH.setText("");
        txtTenLH.setText("");
        cboNhaCC.setSelectedIndex(0);
        hidejbtLH(true);
        hidejbtSX(false);
    }//GEN-LAST:event_jbtThemActionPerformed

    private void jbtXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXoaActionPerformed
        // TODO add your handling code here:
        int rowselected = tblLoaihang.getSelectedRow();
        String id = tblLoaihang.getValueAt(tblLoaihang.getSelectedRow(), 1).toString();
        boolean Status = new LoaiHang().xoaLoaiHang(id);
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không",
                "Xóa dữ liệu", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Xóa loại hàng " + txtTenLH.getText() + " thành công");
            Vector<String> v = new Vector<>();
            v.add(this.cboNhaCC.getSelectedItem().toString());
            v.add(txtMaLH.getText());
            v.add(txtTenLH.getText());
            data.remove(v);
            tblLoaihang.updateUI();

        }


    }//GEN-LAST:event_jbtXoaActionPerformed

    private void jbtSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSuaActionPerformed
        // TODO add your handling code here:
        int row = tblLoaihang.getSelectedRow();
        String id = tblLoaihang.getValueAt(row, 1).toString();
        boolean Status = new LoaiHang().suaLoaiHang(id, txtTenLH.getText());
        if (Status == true) {
            Vector<String> v = new Vector<>();
            v.add(this.cboNhaCC.getSelectedItem().toString());
            v.add(txtMaLH.getText());
            v.add(txtTenLH.getText());
            data.add(v);
            data.remove(row);
            tblLoaihang.updateUI();
        }
    }//GEN-LAST:event_jbtSuaActionPerformed

    private void cboNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNhaCCActionPerformed
        // TODO add your handling code here:
        if (cboNhaCC.getSelectedIndex() == 0) {
            data.removeAllElements();
            String sql = "select ccLoaiHang.maNhaCC, ccLoaiHang.maLH, tenLH\n"
                    + "                from ccLoaiHang\n"
                    + "                inner join LoaiHang on ccLoaiHang.maLH = LoaiHang.maLH\n"
                    + "                inner join NhaCC on ccLoaiHang.maNhaCC = NhaCC.maNhaCC\n"
                    + "                where LoaiHang.status = 1\n"
                    + "                order by ccLoaiHang.maNhaCC asc";
            try {

                Statement stm = cnt.createStatement();
                ResultSet rs = stm.executeQuery(sql);

                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    data.add(v);
                    tblLoaihang.updateUI();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Có lỗi khi lấy dữ liệu từ database!");
            }
        } else if (cboNhaCC.getSelectedIndex() == 1) {
            data.removeAllElements();
            try {
                Statement stm = cnt.createStatement();
                ResultSet rs = stm.executeQuery("select distinct NhaCC.maNhaCC, ccLoaiHang.maLH, tenLH from ccLoaiHang "
                        + "inner join LoaiHang on ccLoaiHang.maLH = LoaiHang.maLH "
                        + "inner join NhaCC on ccLoaiHang.maNhaCC = NhaCC.maNhaCC "
                        + "where ccLoaiHang.maNhaCC = '" + this.cboNhaCC.getSelectedItem().toString() + "' and LoaiHang.status = 1");
                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    data.add(v);
                    tblLoaihang.updateUI();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi Index == 1");
            }
        } else if (cboNhaCC.getSelectedIndex() == 2) {
            data.removeAllElements();
            try {
                Statement stm = cnt.createStatement();
                ResultSet rs = stm.executeQuery("select distinct NhaCC.maNhaCC, ccLoaiHang.maLH, tenLH from ccLoaiHang inner join LoaiHang on ccLoaiHang.maLH = LoaiHang.maLH inner join NhaCC on ccLoaiHang.maNhaCC = NhaCC.maNhaCC where ccLoaiHang.maNhaCC = '" + this.cboNhaCC.getSelectedItem().toString() + "' and LoaiHang.status = 1");
                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    data.add(v);
                    tblLoaihang.updateUI();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi Index == 2");
            }
        } else if (cboNhaCC.getSelectedIndex() == 3) {
            data.removeAllElements();
            try {
                Statement stm = cnt.createStatement();
                ResultSet rs = stm.executeQuery("select distinct NhaCC.maNhaCC, ccLoaiHang.maLH, tenLH from ccLoaiHang inner join LoaiHang on ccLoaiHang.maLH = LoaiHang.maLH inner join NhaCC on ccLoaiHang.maNhaCC = NhaCC.maNhaCC where ccLoaiHang.maNhaCC = '" + this.cboNhaCC.getSelectedItem().toString() + "' and LoaiHang.status = 1");
                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    data.add(v);
                    tblLoaihang.updateUI();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi Index == 3");
            }
        } else if (cboNhaCC.getSelectedIndex() == 4) {
            data.removeAllElements();
            try {
                Statement stm = cnt.createStatement();
                ResultSet rs = stm.executeQuery("select distinct NhaCC.maNhaCC, ccLoaiHang.maLH, tenLH from ccLoaiHang inner join LoaiHang on ccLoaiHang.maLH = LoaiHang.maLH inner join NhaCC on ccLoaiHang.maNhaCC = NhaCC.maNhaCC where ccLoaiHang.maNhaCC = '" + this.cboNhaCC.getSelectedItem().toString() + "' and LoaiHang.status = 1");
                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    data.add(v);
                    tblLoaihang.updateUI();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi Index == 4");
            }
        }

    }//GEN-LAST:event_cboNhaCCActionPerformed

    private void jbtHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHuyActionPerformed
        // TODO add your handling code here:
        getInfo01();
        hidejbtLH(false);
    }//GEN-LAST:event_jbtHuyActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        if (!txtTimKiem.getText().isEmpty()) {
            data.removeAllElements();
            try {
                String sql = "Select ccLoaiHang.maNhaCC, ccLoaiHang.maLH, tenLH "
                        + "from LoaiHang inner join ccLoaiHang on LoaiHang.maLH = ccLoaiHang.maLH "
                        + "where ccLoaiHang.maNhaCC like '%" + txtTimKiem.getText() + "%' "
                        + "or ccLoaiHang.maLH like '%" + txtTimKiem.getText() + "%'  "
                        + "or tenLH like '%" + txtTimKiem.getText() + "%' and LoaiHang.status = 1";

                Statement stm = cnt.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    data.add(v);
                    tblLoaihang.updateUI();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi...");
            }
        } else if (txtTimKiem.getText().isEmpty()) {
            data.removeAllElements();
            loaddata();
        }

    }//GEN-LAST:event_txtTimKiemKeyReleased

//    public void sua() {
    //        int row = tblLoaihang.getSelectedRow();
    //        String id = tblLoaihang.getValueAt(row, 0).toString();
    //        String sql = "update LoaiHang set idLH = '" + txtMaLH.getText() + "', nameLH = '" + txtTenLH.getText()
    //                + "', status = 1 where idLH = '" + id + "'";
    //
    //        try {
    //            PreparedStatement ps = cnt.prepareStatement(sql);
    //            ps.executeQuery();
    //            JOptionPane.showConfirmDialog(this, "Đã sửa thành công");
    //            Vector<String> v = new Vector<>();
    //            v.add(txtMaLH.getText());
    //            v.add(txtTenLH.getText());
    //            data.add(v);
    //            tblLoaihang.updateUI();
    //        } catch (SQLException ex) {
    //            Logger.getLogger(QLLoaiHang.class.getName()).log(Level.SEVERE, null, ex);
    //        }
    //    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QLLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QLLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QLLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QLLoaiHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QLLoaiHang().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNhaCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtHuy;
    private javax.swing.JButton jbtLuu;
    private javax.swing.JButton jbtSua;
    private javax.swing.JButton jbtThem;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JButton jbtXoa;
    private javax.swing.JTable tblLoaihang;
    private javax.swing.JTextField txtMaLH;
    private javax.swing.JTextField txtTenLH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
